### ISSUE TITLE
File translations always download to current working directory

### ISSUE THREAD

**Issue by czan** [crowdin/crowdin-api-client-ruby#17]
When calling the `build_project_file_translation` method, the resulting file is downloaded into the current working directory of the process. This is inconvenient for a few reasons:

1. The filename is determined by the filename in Crowdin, so this runs the risk of overwriting a local file.
2. There is no way to set a different destination, despite this being possible for other API methods (like the `download_*` methods).
3. The only way I can think of to control where the resulting file ends up is to change the working directory with `Dir.chdir`, which has global effects in the process.

It would be really helpful to be able to pass a destination into the `build_project_file_translation` method, and other similar methods.

**Comment by TaniaMal** [comment]
Hi @czan!

We will pass this to our developers and see what we can do about it.

Will keep you posted

**Comment by keshandrr** [comment]
Hello @czan!
Thank you a lot for your suggestions on this one.
Methods like `download_*` usually have a parameter `destination` that defines file download endpoint.
So in this case I forgot to add this parameter.

For now we have 2 cases to work with file downloading:
* Specify the absolute file path as `destination` parameter
* Don't specify `destination` parameter and file will be downloaded to current directory with received filename from a 
Crowdin.

For now I've added this missed parameter for `build_project_file_translation` method and fix will be released soon by #18
I also think about option for downloading file by specifying only path, but filename we will be receive from a Crowdin.

Thank you!

**Comment by czan** [comment]
Perfect! That's exactly the outcome I was hoping for. Thank you! :slightly_smiling_face:
