### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by cmrd-senya** [crowdin/crowdin-api-client-ruby#20]
Hello @keshandrr !

I know that you're  going to add pagination support to the API client.

What is a current state of it? Have you already started working on it?

We could help and contribute the development of pagination support, in case it can speed things up.

But in order to contribute we should coordinate what and how we build to get an acceptable result.

**Comment by keshandrr** [comment]
Hello @cmrd-senya 
Thanks for your interest on this one.
It's partly done from my side, and I think will be released by #19 in next few days
I'll ask for help from your side if need be

**Comment by cmrd-senya** [comment]
@keshandrr I'd be grateful if you let me know when it's ready for code review, I'd like to review the implementation of pagination support

**Comment by keshandrr** [comment]
Hi @cmrd-senya 
Sorry for delay
When you have a chance you can review this PR (FetchAll) https://github.com/crowdin/crowdin-api-client-ruby/pull/22
