### ISSUE TITLE
Auto generated docs

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-ruby#23]
As a Crowdin Ruby API client user, I would like to have online docs to navigate and explore the client resources, methods, parameters, etc.

Examples:
- [Crowdin API Client PHP docs](https://crowdin.github.io/crowdin-api-client-php/packages/Crowdin.html)
- [Crowdin API Client JS docs](https://crowdin.github.io/crowdin-api-client-js/modules.html)
- [Crowdin API Client .NET docs](https://crowdin.github.io/crowdin-api-client-dotnet/api/Crowdin.Api.html)

These docs should be generated using GH Actions and deployed to GH Pages. Workflow example: [docs.yml](https://github.com/crowdin/crowdin-api-client-js/blob/master/.github/workflows/docs.yml)

The possible tool for that is [rdoc](https://github.com/ruby/rdoc).

Steps:

- [ ] Explore tools to generate docs from code, and choose the best one.
- [ ] Create a config and provide a command to generate the docs.
- [ ] If needed, add additional annotations to the API Client code (ignore some unneeded methods in docs, add some method or parameter descriptions, etc).
- [ ] Set up the  GH workflow. @andrii-bodnar can help with that.
- [ ] Set up the GH pages feature for the repo. @andrii-bodnar

**Comment by sabarish98** [comment]
@andrii-bodnar : I would like to work on this, and using tools to generate inline docs is kind of new to me compared to the other contributions, so would appreciate some guidance on this.

1. Explore tools to generate docs from code, and choose the best one - we have rdoc & yard, we can go whichever we want, I am leaning towards yard since it's adoption seems to be more - https://ruby.libhunt.com/compare-yard-vs-rdoc
2. If needed, add additional annotations to the API Client code (ignore some unneeded methods in docs, add some method or parameter descriptions, etc). - I would like some clarity on what all methods that needed to be covered

For the other steps, I would probably reach out to you  as and when required. Feel free to also provide any other pointers that I need to have in mind before I begin work on this. TIA

**Comment by andrii-bodnar** [comment]
@andrii-bodnar sounds great! Let's try to do that 🙂 

Just checked both the `rdoc` & `yard` and for me, the `yard` looks better (more stars, more recent release)

> I would like some clarity on what all methods that needed to be covered

The most important methods here are methods related to the `api_resources`. The `spec` directory should be ignored since there is no reason to document Unit tests. Also, I am not sure about other parts of the library like `core` and `bin`.

Here is the list of how it's implemented in other Crowdin API Clients:

- **crowdin-api-client-js**
  - [Workflow file](https://github.com/crowdin/crowdin-api-client-js/blob/master/.github/workflows/docs.yml) (`typedoc` is used)
  - [Final result](https://crowdin.github.io/crowdin-api-client-js/modules.html)
- **crowdin-api-client-dotnet**
  - [Workflow file](https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/.github/workflows/docs.yml) (`docfx` is used)
  - [Final result](https://crowdin.github.io/crowdin-api-client-dotnet/api/Crowdin.Api.html)
- **crowdin-api-client-python**
  - [Workflows file](https://github.com/crowdin/crowdin-api-client-python/blob/main/.github/workflows/docs.yml) (`pdoc` is used)
  - [Final result](https://crowdin.github.io/crowdin-api-client-python/)
- **crowdin-api-client-php**
  - [Workflow file](https://github.com/crowdin/crowdin-api-client-php/blob/master/.github/workflows/docs.yml) (`phpdoc` is used)
  - [Final result](https://crowdin.github.io/crowdin-api-client-php/packages/Crowdin.html)

**Comment by sabarish98** [comment]
Thanks for the details @andrii-bodnar. I will get started on this then : )

**Comment by andrii-bodnar** [comment]
@sabarish98 thank you! Please let me know when there you'll need some help

**Comment by sabarish98** [comment]
@andrii-bodnar :  I was exploring using yard, and found that we may need to add annotations across all the files under ApiResources to see at least parameter details. I have added for the `bundles.rb` file and it looks like this.

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/50691454/198719866-a3621456-8dd3-4787-b6ca-07f96a4e8ad3.png">

Just the parameters passed should be enough? or do we need more info? But on either case, I was thinking of adding annotations for the majorly used API endpoints first, and do all the entities iteratively as it would split the files changed across multiple PRs as well,  and it would also be easy for you to review them. What do you think?

**Comment by andrii-bodnar** [comment]
@sabarish98 it looks great! 😃 

We need to add some annotations indeed. The most important methods are those that represent API endpoints (like `add_bundle`, `delete_bundle`, `edit_bundle`, etc.)

It would be great at least to include in annotations an API method name, links, and parameters list if possible.

For example, how it is done in other our API clients:
- https://github.com/crowdin/crowdin-api-client-js/blob/master/src/bundles/index.ts
- https://github.com/crowdin/crowdin-api-client-dotnet/blob/main/src/Crowdin.Api/Bundles/BundlesApiExecutor.cs
- https://github.com/crowdin/crowdin-api-client-python/blob/main/crowdin_api/api_resources/bundles/resource.py
- https://github.com/crowdin/crowdin-api-client-php/blob/master/src/CrowdinApiClient/Api/BundleApi.php

**Comment by andrii-bodnar** [comment]
You can create separate pull requests, or it is also ok to split changes into separate commits inside one big request - this way is also easy to review

**Comment by sabarish98** [comment]
@andrii-bodnar : I got your point, and yes to maintain the consistency with the other clients, we can have the links to the APIs as well.

Do we need to do it all in one shot, in a single PR, because there are around 200+ API methods supported by the client, and adding parameters, links to all of them, will take some time.

Would that be fine?

**Comment by andrii-bodnar** [comment]
@sabarish98 we can start with some of the most important parts - Storage, Project, and Source Files.

Then, create an initial PR, including the GH Workflow (I can help with that and also integrate with GH Pages) just to make these docs work.

As a result, we will have working docs but not fully documented with these annotations yet, and then gradually cover the rest with separate PRs.

**Comment by sabarish98** [comment]
@andrii-bodnar : Alright, I'll get to the implementation of those three APIs then 👍

**Comment by andrii-bodnar** [comment]
@sabarish98 great! you can also leave already done work on bundles

**Comment by andrii-bodnar** [comment]
Hi @sabarish98, do you have some updates on this? Please let me know if you need any assistance here 🙂

**Comment by sabarish98** [comment]
@andrii-bodnar : Opened #32. Please review

Seems like the CI is throwing Rubocop offences for empty lines below module definition without which documentation  comments aren't read properly. I will check this

**Comment by sabarish98** [comment]
@andrii-bodnar : Fixed the offences : ) Let me know if anything needs to be changed with respect to the documentation aspect

**Comment by andrii-bodnar** [comment]
@sabarish98 thanks a lot for your contribution! 🚀 
I will check this out as soon as possible

**Comment by andrii-bodnar** [comment]
@sabarish98 maybe it would be better to close this issue and open a separate issue for annotations adding?

**Comment by sabarish98** [comment]
@andrii-bodnar :  Yes, that makes much more sense. We can have separate issues for annotations

**Comment by andrii-bodnar** [comment]
@sabarish98 I've created a single issue to avoid a large number of similar issues, but added a checklist that will allow marking the completed API resources.
