### ISSUE TITLE
Report Settings Templates API support

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-ruby#24]
**New API endpoints:**
  - [api.projects.reports.settings-templates.getMany](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.reports.settings-templates.getMany)
  - [api.projects.reports.settings-templates.post](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.reports.settings-templates.post)
  - [api.projects.reports.settings-templates.get](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.reports.settings-templates.get)
  - [api.projects.reports.settings-templates.patch](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.reports.settings-templates.patch)
  - [api.projects.settings-templates.delete](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.settings-templates.delete)

These new endpoints should be reflected in this API client and covered by Unit tests.

**Comment by sabarish98** [comment]
I can also take this up @andrii-bodnar , can you assign it to me ?

**Comment by andrii-bodnar** [comment]
@sabarish98 great, thanks a lot!

**Comment by sabarish98** [comment]
@andrii-bodnar : #28 for your review : )
