### ISSUE TITLE
Add Bundle API - mark some parameters as required

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-ruby#25]
[Add Bundle API reference](https://developer.crowdin.com/enterprise/api/v2/#operation/api.projects.bundles.post)

https://github.com/crowdin/crowdin-api-client-ruby/blob/18f977eeb68d30baed7fe95da4545caa937dd3d2/lib/crowdin-api/api_resources/bundles.rb#L18

The following parameters are required by API - `name`, `format`, `sourcePatterns`, `exportPattern`. 

It should be marked as required in the code also and the corresponding error should be raised in case of some parameter absence. (`raise_parameter_is_required_error`)

**Comment by sabarish98** [comment]
@andrii-bodnar : Can you assign this issue to me? I will get the work started on this

**Comment by sabarish98** [comment]
@andrii-bodnar : Raised https://github.com/crowdin/crowdin-api-client-ruby/pull/27 for this. I believe this was the requirement, feel free to let me know if otherwise

**Comment by andrii-bodnar** [comment]
@sabarish98 thank you, I will review it tomorrow
