### ISSUE TITLE
Global retry configuration

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-ruby#30]
**Problem**

There is a possibility to configure retry configuration for requests to handle some exceptions:

```
@crowdin.fetch_all(:list_projects, {}, { request_delay: 2, retries_count: 3, error_messages: ['401'] })
```

But this retry configuration applies only to the `fetch_all` methods and **not to all the API Client methods**.

**Narrative**

We need to make the retry configuration **global** so in this case, we'll be able to configure retry options for any request to Crowdin.

Possible solution: move this configuration to the client configuration level and consider these options in each API request to Crowdin

Also, this feature should be better documented in the Readme.

**Additional info**

Good reference - [Crowdin JS API Client Retry Configuration](https://github.com/crowdin/crowdin-api-client-js#retry-configuration)

**Comment by sabarish98** [comment]
@andrii-bodnar : I can pick this up

**Comment by andrii-bodnar** [comment]
@sabarish98 it is not completed so it would be great if you can pick this up! 🙂

**Comment by sabarish98** [comment]
@andrii-bodnar : Yes, will start working on it. Will reach out if I get any questions

**Comment by andrii-bodnar** [comment]
@sabarish98 awesome, thank you, feel free to ask any questions

**Comment by sabarish98** [comment]
@andrii-bodnar : I made some progress in addressing this issue and pushed a commit with some changes on it. Can you take a look and nudge me if you were thinking of implementing it differently or if this would be okay? Please find the commit here - https://github.com/crowdin/crowdin-api-client-ruby/commit/e5feedd43761041830b86bea3fca56fc65115fa0

**Comment by andrii-bodnar** [comment]
@sabarish98 looks good, thank you!

Here are the changes I'd suggest making:
- reuse the [current retry algorithm](https://github.com/crowdin/crowdin-api-client-ruby/blob/eb1a39253b079f756700d3d7b915e80fffec3a67/lib/crowdin-api/client/client.rb#L129) and avoid code duplication This logic should be extracted to a method.
- Try adding Unit tests for this retry algorithm part.
- Can we add strict typings for the `retry_opts`? To avoid passing some unexpected data.
- Add a separate section to the Readme describing the Retry configuration (after the "Fetch all records" section). [Example](https://github.com/crowdin/crowdin-api-client-js#retry-configuration).
- remove the [mention of the current](https://github.com/crowdin/crowdin-api-client-ruby/blob/main/README.md?plain=1#L173) retry mechanism. We'd like to make the global config a default option, but still need to keep the old one for backward compatibility.

**Comment by sabarish98** [comment]
@andrii-bodnar : Thanks for the inputs, will incorporate them. 

Although I would like some clarity on this - `Can we add strict typings for the retry_opts? To avoid passing some unexpected data.` - Do you want to have some sort of validation for the retry_options while setting them up during configuration of the client, or before retrying the methods?

**Comment by andrii-bodnar** [comment]
@sabarish98 it would be great to have some validation during the configuration of the client

**Comment by andrii-bodnar** [comment]
Hi @sabarish98, how it's going with this issue? Do you need any assistance with that?

**Comment by sabarish98** [comment]
Hi @andrii-bodnar , got busy all last week, so couldn't spend time on this. Ofc, I will reach out if I need any help. Thanks for volunteering to help : )

**Comment by andrii-bodnar** [comment]
@sabarish98 let me know if you need any assistance 🙂
