### ISSUE TITLE
Refactor fetch_all feature

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-ruby#31]
Currently, the list of available methods for the `fetch_all` feature is [hardcoded](https://github.com/crowdin/crowdin-api-client-ruby/blob/18f977eeb68d30baed7fe95da4545caa937dd3d2/lib/crowdin-api/core/fetch_all_extensions.rb). 

It's a bad approach since we need to maintain this list and there is a risk to forget adding some new methods.

We need to refactor this feature and get rid of these hardcoded values. Also, it would be great to somehow validate the passed method (if it supports pagination), or add some graceful exception handling for that.

**Comment by sabarish98** [comment]
This would be interesting to work on. All the method names beginning with `list_`  would support  fetch_all feature? Or is there a further classification in the supported methods? @andrii-bodnar

**Comment by andrii-bodnar** [comment]
@sabarish98 we can rely on the `list_` part of the method name, but the main characteristic of these methods is the ability to be paginated (presence of the `limit` and `offset` parameters)

**Comment by sabarish98** [comment]
@andrii-bodnar : Yes, I understood the pagination aspect, but even if those optional params aren't supplied, we are setting a default value right?

Are you suggesting we use both the method name prefix as well as the presence of these optional params?

**Comment by andrii-bodnar** [comment]
@sabarish98 you're right, the optional `limit` and `offset` parameters could be missing in the request

Probably, it would be enough to check only the name of the method. I hope that all the list methods have the `list_` part 🙂

**Comment by sabarish98** [comment]
@andrii-bodnar : Yeah, probably, the method name alone should be enough. We can also check if all the methods that support pagination has the prefix.

I believe we can also raise the same error which is already being raised if an unsupported method is given.

I would love to work on this, but probably after doing the docs first

**Comment by andrii-bodnar** [comment]
@sabarish98 sure, thank you! So I'll assign this issue to you

**Comment by andrii-bodnar** [comment]
@sabarish98 do you have any progress on this? 
I am going to release a new version of this API client and just wondering if I can wait for this issue before the release

**Comment by sabarish98** [comment]
Hey @andrii-bodnar, when's the plan to release it? I will let you know if this can be done before that or not

**Comment by andrii-bodnar** [comment]
@sabarish98 there's no plan with a strict deadline, but probably the next week would be good for release.

Anyway, I'm not forcing you to finish this issue 🙂 
If you need more time for this then I will just release a new version and then another version will be released.

**Comment by sabarish98** [comment]
@andrii-bodnar : That's fine, I was just juggling a lot of stuff and this got pushed back. Open a PR for this now.

Please check #35 and let me know if anything needs to be changed
