### ISSUE TITLE
Add support for the Notifications API

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-ruby#50]
Crowdin API has a new Notifications API that allows sending notifications to the project and organization members. It would be great to add support for this API in this Crowdin API client.

**API reference:**

- [Send Notification to Authenticated User](https://developer.crowdin.com/api/v2/#operation/api.notify.post) (crowdin.com)
- [Send Notification To Project Members](https://developer.crowdin.com/api/v2/#operation/api.projects.notify.post) (crowdin.com and Crowdin Enterprise)
- [Send Notification To Organization Members](https://developer.crowdin.com/enterprise/api/v2/#operation/api.notify.post) (Crowdin Enterprise)

**Comment by MohanThanigaivelan** [comment]
Hi @andrii-bodnar .  Just for confirmation, nobody else is working on this task right ? I am planning to work on it. Thanks.

**Comment by andrii-bodnar** [comment]
Hi @MohanThanigaivelan, sure, you can take it. Assigning to you, thank you!

**Comment by andrii-bodnar** [comment]
@MohanThanigaivelan any updates on this?

**Comment by MohanThanigaivelan** [comment]
@andrii-bodnar  I have done with the changes . Here is the PR #56 . Let me know your review comments on this .
