### ISSUE TITLE
Add the option to choose between instant file downloading and returning response data

### ISSUE THREAD

**Issue by artem-vavilov** [crowdin/crowdin-api-client-ruby#66]
The response from [Build Project File Translation](https://developer.crowdin.com/api/v2/#operation/api.projects.translations.builds.files.post) contains important `etag` data, which is not accessible through the [`#build_project_file_translation`](https://github.com/crowdin/crowdin-api-client-ruby/blob/main/lib/crowdin-api/api_resources/translations.rb#L43) method, as it returns only the downloaded file's path.

https://github.com/crowdin/crowdin-api-client-ruby/blob/a3110e9d95ccae72d7a975393c86185694824d37/lib/crowdin-api/core/send_request.rb#L46-L52

**Comment by andrii-bodnar** [comment]
Hi @artem-vavilov, thanks for pointing this out! Would you like to open a PR? 🙂 

Check out the [Contribution Guide](https://github.com/crowdin/crowdin-api-client-ruby/blob/main/CONTRIBUTING.md) for more details.
