### ISSUE TITLE
Add Request Timeout configuration

### ISSUE THREAD

**Issue by artem-vavilov** [crowdin/crowdin-api-client-ruby#86]
Currently, the request timeout is disabled ([timeout: nil](https://github.com/rest-client/rest-client/blob/cf3e5a115bcdb8f3344aeac0e45b44d67fac1a42/lib/restclient/request.rb#L41-L43)) and can't be configured which can lead to indefinite response waits.

https://github.com/crowdin/crowdin-api-client-ruby/blob/a383c3c8b80e9e32f44162852c1dc5433c291422/lib/crowdin-api/client/configuration.rb#L18-L24

https://github.com/crowdin/crowdin-api-client-ruby/blob/a383c3c8b80e9e32f44162852c1dc5433c291422/lib/crowdin-api/client/client.rb#L164

**Comment by andrii-bodnar** [comment]
Available in [1.10.0](https://github.com/crowdin/crowdin-api-client-ruby/releases/tag/1.10.0)
