### ISSUE TITLE
Support new 'Remove String Approvals' API endpoint

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/crowdin-api-client-ruby#94]
Crowdin has recently introduced a new [Remove String Approvals](https://support.crowdin.com/developer/api/v2/#tag/String-Translations/operation/api.projects.approvals.deleteMany) API endpoint that allows you to remove approvals for a specific string in a project for all languages in one request.

Also, the [Delete String Translations](https://support.crowdin.com/developer/api/v2/#tag/String-Translations/operation/api.projects.translations.deleteMany) API endpoint has been updated: `languageId` parameter is now optional.

These changes are not yet supported in the Crowdin API clients and we need to add support for them.

**Comment by IgorFroehner** [comment]
Hello! I'm working on this, this is my WIP PR for now. 

But I'm getting a Internal Server Error on my requests, not sure if I'm doing anything wrong.
```
DELETE https://api.crowdin.com/api/v2/projects/<project-id>/approvals?stringId=<string-id>

{
    "error": {
        "message": "Internal Server Error",
        "code": 500
    }
}
```

**Comment by andrii-bodnar** [comment]
Hi @IgorFroehner, thanks for reporting this! This is a known issue and the team is already working on it. I believe it shouldn't block the implementation on the Client side.
